#ifndef _PRJ_CFG_H
#define _PRJ_CFG_H

#define CYCLE_TIME_IN_MICROS (50000L)
#define CFG_BLINKING_TIME_IN_MS (1000L)
#define CFG_BLINKING_PROGRAM_CYCLES ((CFG_BLINKING_TIME_IN_MS*1000L)/(CYCLE_TIME_IN_MICROS))
#define CFG_BLINKING_LED (0)

#endif /* _PRJ_CFG_H */

